services:
  # --- Base de donn√©es MySQL ---
  database:
    image: mysql:8.1
    container_name: herfrequencies_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: herfrequencies
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # --- Mailpit pour capturer les mails en dev ---
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: always
    ports:
      - "8025:8025"  # interface web
      - "1025:1025"  # SMTP pour Symfony

volumes:
  db_data: {}
